#!/bin/sh
# Substitute runtime environment variables into env.js so the SPA can read
# configuration without rebuilding. Only variables listed here are exposed.
set -eu

: "${VITE_API_URL:=}"

ENV_JS_PATH="/usr/share/nginx/html/env.js"

cat > "$ENV_JS_PATH" <<EOF
// Auto-generated by docker-entrypoint.sh at container start.
window.__ENV__ = {
  VITE_API_URL: "${VITE_API_URL}"
};
EOF

exec nginx -g 'daemon off;'
